language: scala
jdk: openjdk8
script:
- sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck "^ scripted"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
matrix:
  include:
  - os: linux
  - os: windows
    language: bash
    env: JDK="adopt@1.8.0-222"
    before_script:
    - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
    - source .install-jdk-travis.sh
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/3b15595bbc0c4ff97325b618322367f02e136a62/sbt && chmod +x ./sbt
    script:
    - ./sbt "^ scripted"
